---
spring:
  h2:
    console:
      - enabled: true
  datasource:
    - url: ${CLEARDB_DATABASE_URL}
    - username: admin
    - password:
    - driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      - ddl-auto: create-drop
courses:
  courseDisplayLimit: 20
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error